### PR TITLE
Small changes to make the tests run (Not all tests are passing)

### PR DESCRIPTION
**Pull request by tmahmood**
Hi, 
I have made some small changes, to make the tests run. All tests are still not working due to `expect_event` failing to detect any events correctly OR events are not emitted correctly. Can you shade some light on that?

### CODE REVIEW

**Comment by octaltree** [comment]
Thanks for the pr. As you say, dev doesn't pass the test, it's being actively implemented as 1.25 support. On the other hand, I am interested in your problem statement.
* When does ResInitial not have params? In dev? In master? In what way?
* commit event was added in 1.25. Is there a case where an error occurs in master?

**Comment by tmahmood** [comment]
Hi,
I am working on the dev repo. 

Sorry if I was not clear on my PR comment.

I am talking about the response string coming from the playwright driver, not playwright rust.

**Comment by tmahmood** [comment]
Hi,
I am working on the dev repo. Sorry for not being clear on my PR comment.

> commit event was added in 1.25. Is there a case where an error occurs in master?

No. 

> When does ResInitial not have params? In dev? In master? In what way?

I am talking about the response coming from the playwright driver, not playwright rust. 

When we try to close the browser using close, playwright-driver responds with this:

```
[2022-08-22T05:20:00Z DEBUG playwright::imp::core::transport] RECV {"guid":"browser-context@16fcfb31801cba8c19bc2d2d0fe94a0a","method":"close"}
```

Notice no `params` in the response. Which causes the deserailzer to fail, hence we receive the following error. 

```
called `Result::unwrap()` on an `Err` value: Transport(Serde(Error("data did not match any variant of untagged enum Res", line: 0, column: 0)))
thread 'tests::closing' panicked at 'called `Result::unwrap()` on an `Err` value: Transport(Serde(Error("data did not match any variant of untagged enum Res", line: 0, column: 0)))', src/main.rs:91:15
```

My commit solves this 


From my investigation, I believe most of the functions are working, but `expect_event` is failing to detect Page Event Types, which is why tests are failing with timeout error.

**Comment by tmahmood** [comment]
Hi, another change that resolves issues with some of the Page Events not working.

**Comment by tmahmood** [comment]
Hi @octaltree 
All the tests are now passing, except one. Please review my code and let me know if it's all good.

**Comment by octaltree** [comment]
Thank you. I figured out the problem, which is helpful because it was something I had to work on as soon as I was done with the api generation.

**Comment by tmahmood** [comment]
Great! Thank you

**Pull request merged**
